name: PR checker

on:
  pull_request:
    branches: [main, develop]
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Solution and Run Tests
      id: build
      run: dotnet test --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"
    # - name: Combine Coverage Reports
    #   uses: danielpalme/ReportGenerator-GitHub-Action@c4c5175a441c6603ec614f5084386dabe0e2295b
    #   with:
    #       reports: "**/*.cobertura.xml"
    #       targetdir: "${{ github.workspace }}"
    #       reporttypes: "Cobertura"
    #       verbosity: "Info"
    #       title: "Code Coverage"
    #       toolpath: "reportgeneratortool"
    # - name: Upload Combined Coverage XML
    #   uses: actions/upload-artifact@v4
    #   with:
    #       name: coverage
    #       path: ${{ github.workspace }}/Cobertura.xml
    #       retention-days: 5
    # - name: Publish Code Coverage Report
    #   uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95
    #   with:
    #       filename: "Cobertura.xml"
    #       badge: true
    #       fail_below_min: false # just informative for now
    #       format: markdown
    #       hide_branch_rate: false
    #       hide_complexity: false
    #       indicators: true
    #       output: both
    #       thresholds: "10 30"
    # - name: Add Coverage PR Comment
    #   uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
    #   if: github.event_name == 'pull_request'
    #   with:
    #       recreate: true
    #       path: code-coverage-results.md
    # - name: Upload Test Result Files
    #   uses: actions/upload-artifact@v4
    #   with:
    #       name: test-results
    #       path: ${{ github.workspace }}/**/TestResults/**/*
    #       retention-days: 5
          
    # - name: Publish Test Results
    #   uses: EnricoMi/publish-unit-test-result-action@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6
    #   if: always()
    #   with:
    #       trx_files: "${{ github.workspace }}/**/*.trx"

    - name: Delete previous comments
      uses: actions/github-script@v6
      with:
        script: |
          const comments = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const validationComments = comments.data.filter(comment => 
            comment.user.login === 'github-actions[bot]' && 
            (comment.body.includes('🚨 The PR title or description is invalid') || 
             comment.body.includes('✅ PR title and description are valid'))
          );

          for (const comment of validationComments) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id,
            });
          }

    - name: Validate PR title and description
      id: validate
      run: |
        # Fetching PR title and description
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"
        echo "PR title - $PR_TITLE - ${#PR_TITLE}"
        echo "PR body - $PR_BODY - ${#PR_BODY}"

        # Define the regex pattern for the PR title
        TITLE_REGEX=".*MT-[0-9]+.*"
        
        # Validate the PR title using the regex
        if [[ ! "$PR_TITLE" =~ $TITLE_REGEX || ${#PR_TITLE} -lt 10 ]]; then
          echo "PR title does not match the required format: [MT-<number> followed by at least 10 characters]"
          echo "::set-output name=valid::false"
        elif [[ ${#PR_BODY} -lt 15 ]]; then
          echo "PR description is too short"
          echo "::set-output name=valid::false"
        else
          echo "PR is valid"
          echo "::set-output name=valid::true"
        fi

    - name: Comment on PR if validation fails
      if: steps.validate.outputs.valid == 'false'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🚨 The PR title or description is invalid. Please ensure the title has LPC number. The description should be at least 10 characters long. ![Failed](https://raw.githubusercontent.com/batonkarton/mentoad-auto-parts-store/main/.github/failed.png)"
          })

    - name: Comment on PR if validation succeeds
      if: steps.validate.outputs.valid == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "✅ PR title and description are valid! Great job! ![Success](https://raw.githubusercontent.com/batonkarton/mentoad-auto-parts-store/main/.github/success.png)"
          })

    - name: Check validation result
      if: steps.validate.outputs.valid == 'false'
      run: |
        echo "Validation failed. Failing the pipeline."
        exit 1